### ISSUE TITLE
Available for purchase?

### ISSUE THREAD

**Issue by hydrotik** [kenkawakenkenke/tempescope#1]
I signed up for your newsletter a while back (I did again just in case;) and just curious when you will have the tempescope available for sale? :) Sorry for posting this here!

**Comment by kenkawakenkenke** [comment]
Sorry, I only noticed your message.
Yes, we're almost ready for our crowd funding campaign launch.
We are aiming to debut the finished product in the Bay Area Maker's Faire (although, as things tend to go, it may get delayed)
Thanks!

**Comment by hydrotik** [comment]
No problem. I figured this might be a strange place to pose the question, but figured I'd try anyway:)  That is great news and I hope you post an update either here or on the README file when you start your Kickstarter campaign. I will be sure to support! If you don't make it to Bay area, then maybe you will consider attending the NYC Faire. Thanks again!
