### ISSUE TITLE
More descriptive parts list

### ISSUE THREAD

**Issue by joejuzl** [kenkawakenkenke/tempescope#6]
Hi there,

I was wondering if you could make the parts list a bit more descriptive.
It's hard to know what some components are, e.g. HPH05001M, especially when in a different country.

Thanks! 

Joe

**Comment by sergio-daniels** [comment]
This is kind a transformer which will convert the input voltage to 12 volt.
I used this item to convert the 24V input to 12 Volt
http://www.aliexpress.com/item/DC-DC-Auto-Boost-Buck-adjustable-step-down-Converter-XL6009-Module-Solar-Voltage/2036629248.html
See image: https://www.facebook.com/photo.php?fbid=10153569307734378&set=ms.c.eJxlzjEOACAMAsAfGZpaof~%3B~%3BmMZJ24XhQgIGC4~_VDtKnU8MeYZOTvyhqJ60Jqihbp4vKlnAfbsvFJHI~-.bps.a.10153569306154378.1073741825.846449377&type=1&theater

**Comment by joejuzl** [comment]
Thanks Sergio!

Unfortunately I can't see the facebook picture, maybe it's only shared with your friends?

Also, do you happen to know what the 941H-2C-5D, 78XXS and, TD62083 are used for?

Thanks again,

Joe

**Comment by sergio-daniels** [comment]
Hi Joel,
i'm not a FB friend. Have a look at my github repository wiki you find all the Images there as well.
https://github.com/sergio-daniels/tempescope/wiki/0.1-Images
941H-2C-5D is just a relay you can use any relay which matches the voltage for the coil and the voltage to Switch. 78xxS is the voltage Regulator which gives you the 5 Volt for your logic. The TD62083 is your darlington sink Driver to protect your microcontroller Outputs so you can draw more current wich you need.
Kind regards
Sergio

**Comment by joejuzl** [comment]
Thanks you again Sergio, you've been really helpful. I am looking to start building soon.
The pictures are great by the way, looks like you've done a really good job.
